name: Update Supporters List
description: Fetch supporter names from a JSON URL and update README.md between markers

inputs:
  files-to-update:
    required: false
    description: List of files to update
    default: |
      - README.md
  fail-on-missing-markers:
    required: false
    description: Fail if markers are missing
    default: 'true'
  start-marker:
    required: false
    description: Start marker for replacement
    default: '<!-- marker:patrons-start -->'
  end-marker:
    required: false
    description: End marker for replacement
    default: '<!-- marker:patrons-end -->'
  git-email:
    required: false
    description: Email for git config
    default: 'actions@github.com'

runs:
    using: 'node20'
    main: update-patrons.mjs
