name: "Release"

permissions: write-all

on:
  push:
    branches:
      - main

env:
  # renovate: datasource=node-version depName=node versioning=node
  NODE_VERSION: 24

jobs:
  Release:
    runs-on: meza-ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Validate Action
        uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7 # v3.1.1
        with:
          file: action.yml
          schema: https://raw.githubusercontent.com/SchemaStore/schemastore/773fe876b57bb3d35693177b626164570a6bac49/src/schemas/json/github-action.json

      - name: Install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: latest
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: "🧵 Install semantic release"
        run: npm i --location=global @meza/mezas-conventional-changelog semantic-release semantic-release-discord-notifier conventional-changelog-conventionalcommits @semantic-release/github @semantic-release/changelog @semantic-release/exec semantic-release-export-data semantic-release-discord

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: npx semantic-release
