name: "Release"

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Action
        uses: meza/action-validate-action@v1.0.4
      - name: Set up node
        uses: meza/action-setup-node-pnpm@main
        with:
          install: 'true'
          node-version: '20'
      - name: Build
        run: pnpm build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
